version: '3.5'

services:
  web:
    container_name: chameleon_web
    image: nginx:latest
    ports:
      - "88:80"
    volumes:
      - ../:/var/www/project:delegated
      - ./nginx/site.conf:/etc/nginx/conf.d/site.conf
    links:
      - php
    networks:
      - chameleon-network

  php:
    container_name: chameleon_php
    build: ./php
    volumes:
      - ../:/var/www/project:delegated
    networks:
      - chameleon-network

networks:
    chameleon-network:
        driver: bridge
