version: '3.5'

services:
  db:
    container_name: chameleon_db
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db_data5.6:/var/lib/mysql
    networks:
      chameleon-network:
        ipv4_address: 172.19.0.15
