index:
   path: /
   controller: App\Controller\DefaultController::index

dashboard:
  path: /dashboard
  controller: App\Controller\DashboardController::index

simulation_forms_page:
  path: /simulation-forms/page/{page}
  controller: App\Controller\SimulationFormsController::index
  requirements:
    page: '\d+'
  defaults:
    page: 1

simulation_forms_fresh:
  path: /simulation-forms/fresh/{id}
  controller: App\Controller\SimulationFormsController::fresh
  requirements:
    id: '\d+'
  defaults:
    id: 1

simulation_forms_edit:
  path: /simulation-forms/edit/{simulation}
  controller: App\Controller\SimulationFormsController::edit

api:
  path: /api/{category?}/{token}
  controller: App\Controller\ApiController::index
  defaults:
    category: ''
    token: ''
  requirements:
    token: .*
